name: Set Branch Protection

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/branch-protection.yml'

jobs:
  set-branch-protection:
    runs-on: ubuntu-latest
    if: github.repository_owner == github.actor # Only run for repo owners

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set Branch Protection
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;

            // Set branch protection rules for main branch
            await github.rest.repos.updateBranchProtection({
              owner,
              repo,
              branch: 'main',
              required_status_checks: {
                strict: true,
                contexts: ['test', 'lint', 'require-tests']
              },
              enforce_admins: false,
              required_pull_request_reviews: {
                dismissal_restrictions: {},
                dismiss_stale_reviews: true,
                require_code_owner_reviews: false,
                required_approving_review_count: 1,
              },
              restrictions: null
            });

            console.log('Branch protection rules have been set for main branch');
